# Generated by Django 5.1.7 on 2025-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
