# Generated by Django 5.2 on 2025-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_dish_image_url_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
